[package]
name = "nogame_fixed"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.5.3"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

